version: "3"

networks:
  laravel:
  
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ../Code/:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
      
  php74:
#    image: php:7.4-fpm-alpine
    build:
      context: build74
      dockerfile: Dockerfile
    container_name: php74
    hostname: homestead
    volumes: 
      - ../Code/:/var/www
    networks: 
      - laravel
    user: "1000:1000"

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "33060:3306"
    volumes:
      - ./mariadb/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel  
